name: Publish Package to npmjs

on:
  workflow_dispatch:
    inputs:
      VER:
        description: 'VER'
        required: true
        default: 'VER'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "{
  "name": "paddy-oss",
  "version": "${{ github.event.inputs.VER }}",
  "private": false
}" >> package.json
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
